name: NPM Typescript CI/CD Pipeline

on:
  push:
    branches:
      - dev
      # - main   # later toevoegen voor productie
  pull_request:
    branches:
      - dev
      # - main   # later toevoegen voor productie

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [react-server, react-app]

    defaults:
      run:
        working-directory: ${{ matrix.service }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ${{ matrix.service }}/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: TypeScript build
        run: npm run build

      # - name: Run tests
       #  run: npm test --if-present
        
      - name: NPM Audit
        run: npm audit --audit-level=high

  sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        service: [react-server, react-app]

    defaults:
      run:
        working-directory: ${{ matrix.service }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          path: ${{ matrix.service }}
          output-file: sbom-${{ matrix.service }}.spdx.json
          artifact-name: sbom-${{ matrix.service }}

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-artifact-${{ matrix.service }}
          path: sbom-${{ matrix.service }}.spdx.json

  security:
    name: CVE Scan
    runs-on: ubuntu-latest
    needs: sbom
    strategy:
      matrix:
        service: [react-server, react-app]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Download SBOM artifact
        uses: actions/download-artifact@v4
        with:
          name: sbom-artifact-${{ matrix.service }}

      - name: Scan SBOM for CVEs
        uses: anchore/scan-action@v6
        with:
          sbom: "sbom-${{ matrix.service }}.spdx.json"
          severity-cutoff: high
          fail-build: true

  deploy:
    name: Deploy via Portainer
    runs-on: ubuntu-latest
    needs: security

    steps:
      - name: Deploy to Portainer
        run: |
          curl -X POST ${{ secrets.PORTAINER_WEBHOOK_URL }}
